//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibPrintManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Message1 { get; set; }
        public int JobId { get; set; }
        public System.DateTime SendTime { get; set; }
        public int SenderId { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
